# Generated by Django 5.0.6 on 2024-05-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_produccion', '0003_actor_director_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='contents', to='api_produccion.actor'),
        ),
        migrations.AddField(
            model_name='content',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='contents', to='api_produccion.director'),
        ),
        migrations.AddField(
            model_name='content',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='contents', to='api_produccion.genre'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
